// Mocks generated by Mockito 5.4.6 from annotations
// in infytel_test/test/mocks/api_client_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:infytel_test/core/service/api_client.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiResponse_0 extends _i1.SmartFake implements _i2.ApiResponse {
  _FakeApiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i2.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i4.Future<_i2.ApiResponse> get(
    String? endpoint, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#get, [endpoint], {#headers: headers}),
            returnValue: _i4.Future<_i2.ApiResponse>.value(
              _FakeApiResponse_0(
                this,
                Invocation.method(#get, [endpoint], {#headers: headers}),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse>);

  @override
  _i4.Future<_i2.ApiResponse> post(
    String? endpoint, {
    Map<String, String>? headers,
    dynamic body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [endpoint],
              {#headers: headers, #body: body},
            ),
            returnValue: _i4.Future<_i2.ApiResponse>.value(
              _FakeApiResponse_0(
                this,
                Invocation.method(
                  #post,
                  [endpoint],
                  {#headers: headers, #body: body},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse>);

  @override
  _i4.Future<_i2.ApiResponse> put(
    String? endpoint, {
    Map<String, String>? headers,
    dynamic body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [endpoint],
              {#headers: headers, #body: body},
            ),
            returnValue: _i4.Future<_i2.ApiResponse>.value(
              _FakeApiResponse_0(
                this,
                Invocation.method(
                  #put,
                  [endpoint],
                  {#headers: headers, #body: body},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse>);

  @override
  _i4.Future<_i2.ApiResponse> patch(
    String? endpoint, {
    Map<String, String>? headers,
    dynamic body,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [endpoint],
              {#headers: headers, #body: body},
            ),
            returnValue: _i4.Future<_i2.ApiResponse>.value(
              _FakeApiResponse_0(
                this,
                Invocation.method(
                  #patch,
                  [endpoint],
                  {#headers: headers, #body: body},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse>);

  @override
  _i4.Future<_i2.ApiResponse> delete(
    String? endpoint, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [endpoint], {#headers: headers}),
            returnValue: _i4.Future<_i2.ApiResponse>.value(
              _FakeApiResponse_0(
                this,
                Invocation.method(#delete, [endpoint], {#headers: headers}),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse>);
}
